// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: School.proto
// Protobuf Java Version: 4.28.2

package com.zahid.protobuf.proto;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  java.util.List<com.zahid.protobuf.proto.Student> 
      getStudentList();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  com.zahid.protobuf.proto.Student getStudent(int index);
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  java.util.List<? extends com.zahid.protobuf.proto.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  com.zahid.protobuf.proto.StudentOrBuilder getStudentOrBuilder(
      int index);
}
