// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: School.proto
// Protobuf Java Version: 4.28.2

package come.zahid;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  java.util.List<come.zahid.Student> 
      getStudentList();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  come.zahid.Student getStudent(int index);
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  java.util.List<? extends come.zahid.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .protobuf.Student student = 1;</code>
   */
  come.zahid.StudentOrBuilder getStudentOrBuilder(
      int index);
}
